package io.kjs.vm

import io.kjs.runtime.JsValues
import io.kjs.runtime.Undefined

/**
 * Static bridge methods called from JIT-generated bytecode.
 *
 * Keeping these as `static` Kotlin functions with plain `Any?` signatures lets the
 * JIT emit simple INVOKESTATIC calls. Each method is small and monomorphic enough
 * for HotSpot's C2 to inline them back into the generated code.
 */
object JitBridge {
    @JvmField
    val UNDEFINED: Any? = Undefined

    @JvmStatic fun toBool(v: Any?): Boolean = JsValues.toBool(v)

    @JvmStatic fun toNumberBoxed(v: Any?): Any? = JsValues.toNumber(v)

    @JvmStatic fun add(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) (l + r)
        else if (l is String || r is String) JsValues.toStr(l) + JsValues.toStr(r)
        else JsValues.toNumber(l) + JsValues.toNumber(r)

    @JvmStatic fun sub(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l - r else JsValues.toNumber(l) - JsValues.toNumber(r)

    @JvmStatic fun mul(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l * r else JsValues.toNumber(l) * JsValues.toNumber(r)

    @JvmStatic fun div(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l / r else JsValues.toNumber(l) / JsValues.toNumber(r)

    @JvmStatic fun mod(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l % r else JsValues.toNumber(l) % JsValues.toNumber(r)

    @JvmStatic fun neg(v: Any?): Any? = -JsValues.toNumber(v)
    @JvmStatic fun not(v: Any?): Any? = !JsValues.toBool(v)
    @JvmStatic fun typeofOp(v: Any?): Any? = JsValues.typeOf(v)

    @JvmStatic fun eq(l: Any?, r: Any?): Any? = JsValues.looseEq(l, r)
    @JvmStatic fun neq(l: Any?, r: Any?): Any? = !JsValues.looseEq(l, r)
    @JvmStatic fun seq(l: Any?, r: Any?): Any? = JsValues.strictEq(l, r)
    @JvmStatic fun sneq(l: Any?, r: Any?): Any? = !JsValues.strictEq(l, r)

    @JvmStatic fun lt(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l < r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a < b }

    @JvmStatic fun le(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l <= r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a <= b }

    @JvmStatic fun gt(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l > r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a > b }

    @JvmStatic fun ge(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l >= r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a >= b }

    /** Read a pooled constant from the closure's compiled bytecode. */
    @JvmStatic fun constOf(c: VmClosure, idx: Int): Any? = c.bc.constants[idx]
    @JvmStatic fun strOf(c: VmClosure, idx: Int): Any? = c.bc.strings[idx]
}
