package io.kjs.vm

import io.kjs.runtime.JsValues
import io.kjs.runtime.Undefined

/**
 * Static bridge methods called from JIT-generated bytecode.
 *
 * Keeping these as `static` Kotlin functions with plain `Any?` signatures lets the
 * JIT emit simple INVOKESTATIC calls. Each method is small and monomorphic enough
 * for HotSpot's C2 to inline them back into the generated code.
 */
object JitBridge {
    @JvmField
    val UNDEFINED: Any? = Undefined

    @JvmStatic fun toBool(v: Any?): Boolean = JsValues.toBool(v)

    /** Unbox to primitive double. Used by JIT to pull a value into a D slot / D operation. */
    @JvmStatic fun toD(v: Any?): Double = JsValues.toNumber(v)

    /** Double → bool conversion with JS semantics (NaN and 0.0 → false). */
    @JvmStatic fun dToBool(d: Double): Boolean = !(d.isNaN() || d == 0.0)

    @JvmStatic fun toNumberBoxed(v: Any?): Any? = JsValues.toNumber(v)

    @JvmStatic fun add(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) (l + r)
        else if (l is String || r is String) JsValues.toStr(l) + JsValues.toStr(r)
        else JsValues.toNumber(l) + JsValues.toNumber(r)

    @JvmStatic fun sub(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l - r else JsValues.toNumber(l) - JsValues.toNumber(r)

    @JvmStatic fun mul(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l * r else JsValues.toNumber(l) * JsValues.toNumber(r)

    @JvmStatic fun div(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l / r else JsValues.toNumber(l) / JsValues.toNumber(r)

    @JvmStatic fun mod(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l % r else JsValues.toNumber(l) % JsValues.toNumber(r)

    @JvmStatic fun neg(v: Any?): Any? = -JsValues.toNumber(v)
    @JvmStatic fun not(v: Any?): Any? = !JsValues.toBool(v)
    @JvmStatic fun typeofOp(v: Any?): Any? = JsValues.typeOf(v)

    @JvmStatic fun eq(l: Any?, r: Any?): Any? = JsValues.looseEq(l, r)
    @JvmStatic fun neq(l: Any?, r: Any?): Any? = !JsValues.looseEq(l, r)
    @JvmStatic fun seq(l: Any?, r: Any?): Any? = JsValues.strictEq(l, r)
    @JvmStatic fun sneq(l: Any?, r: Any?): Any? = !JsValues.strictEq(l, r)

    @JvmStatic fun lt(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l < r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a < b }

    @JvmStatic fun le(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l <= r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a <= b }

    @JvmStatic fun gt(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l > r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a > b }

    @JvmStatic fun ge(l: Any?, r: Any?): Any? =
        if (l is Double && r is Double) l >= r
        else { val a = JsValues.toNumber(l); val b = JsValues.toNumber(r); !a.isNaN() && !b.isNaN() && a >= b }

    /** Read a pooled constant from the closure's compiled bytecode. */
    @JvmStatic fun constOf(c: VmClosure, idx: Int): Any? = c.bc.constants[idx]
    @JvmStatic fun strOf(c: VmClosure, idx: Int): Any? = c.bc.strings[idx]

    /**
     * Load a global/lexically-visible binding by name. Mirrors the interpreter's
     * `Op.LOAD_GLOBAL` semantics: throws ReferenceError if missing and not
     * tolerated, otherwise returns the value (possibly Undefined).
     */
    @JvmStatic fun loadGlobal(vm: Vm, closure: VmClosure, nameIdx: Int, tolerate: Int): Any? {
        val name = closure.bc.strings[nameIdx]
        val e = closure.closureEnv ?: vm.realm.globalEnv
        if (!e.has(name)) {
            if (tolerate != 0) return Undefined
            jsThrowName(vm.realm, "ReferenceError", "$name is not defined")
        }
        return e.get(name)
    }

    /**
     * LOAD_PROP fast path.  Walks the same code path the interpreter does:
     * goes through the PropIc slot stored in `closure.bc.caches[pc]`, which
     * remembers the monomorphic shape/owner — highly inline-friendly for
     * HotSpot once the site is hot.
     *
     * For non-JsObject receivers we fall back to the generic prop lookup
     * (`loadPropGeneric`), which handles Strings/Numbers/Booleans via their
     * corresponding prototypes.
     */
    @JvmStatic fun loadProp(vm: Vm, closure: VmClosure, pc: Int, obj: Any?, nameIdx: Int): Any? {
        val name = closure.bc.strings[nameIdx]
        if (obj is io.kjs.runtime.JsObject) {
            var caches = closure.bc.caches
            if (caches == null) { caches = arrayOfNulls<Any?>(closure.bc.size); closure.bc.caches = caches }
            var ic = caches[pc] as? PropIc
            if (ic == null) { ic = PropIc(); caches[pc] = ic }
            return ic.get(obj, name) { o, n -> if (o == null) Undefined else o.get(n) }
        }
        return loadPropGeneric(vm, obj, name)
    }

    @JvmStatic fun loadPropGeneric(vm: Vm, obj: Any?, name: String): Any? = when (obj) {
        null -> jsThrowTypeError(vm.realm, "Cannot read property '$name' of null")
        Undefined -> jsThrowTypeError(vm.realm, "Cannot read property '$name' of undefined")
        is String -> stringPropFor(vm, obj, name)
        is io.kjs.runtime.JsObject -> obj.get(name)
        is Double, is Int, is Long -> vm.realm.numberProto.get(name)
        is Boolean -> vm.realm.booleanProto.get(name)
        else -> Undefined
    }

    private fun stringPropFor(vm: Vm, s: String, key: String): Any? {
        val idx = key.toIntOrNull()
        if (idx != null && idx in s.indices) return s[idx].toString()
        if (key == "length") return s.length.toDouble()
        return vm.realm.stringProto.get(key)
    }

    /**
     * Invoke a callable value as a plain function call. Used by the JIT for
     * `Op.CALL` (the global-`this` case). `args` has already been assembled
     * by the generated code.
     */
    @JvmStatic fun invokeCall(vm: Vm, callee: Any?, args: Array<Any?>): Any? {
        val fn = callee as? io.kjs.runtime.JsFunction
            ?: jsThrowTypeError(vm.realm, "value is not a function")
        return vm.invokeFast(fn, vm.realm.globalObject, args)
    }

    /**
     * Stack-order variant: parameters laid out as the JIT wants them on the
     * JVM stack (args, callee, vm). Equivalent to [invokeCall].
     */
    @JvmStatic fun invokeCall2(args: Array<Any?>, callee: Any?, vm: Vm): Any? =
        invokeCall(vm, callee, args)

    /** Convenience: build an Object[] of size n from the top N items of an already-collected list. */
    @JvmStatic fun argsOf0(): Array<Any?> = emptyArray()
    @JvmStatic fun argsOf1(a0: Any?): Array<Any?> = arrayOf(a0)
    @JvmStatic fun argsOf2(a0: Any?, a1: Any?): Array<Any?> = arrayOf(a0, a1)
    @JvmStatic fun argsOf3(a0: Any?, a1: Any?, a2: Any?): Array<Any?> = arrayOf(a0, a1, a2)
    @JvmStatic fun argsOf4(a0: Any?, a1: Any?, a2: Any?, a3: Any?): Array<Any?> = arrayOf(a0, a1, a2, a3)
}
